// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASvV10gIi5HMkCKmcW-erD7arwltzycxw',
    appId: '1:364268621894:web:f781f49e6df0e55628ba47',
    messagingSenderId: '364268621894',
    projectId: 'socialmediaapp-a0b5f',
    authDomain: 'socialmediaapp-a0b5f.firebaseapp.com',
    storageBucket: 'socialmediaapp-a0b5f.firebasestorage.app',
    measurementId: 'G-P1KHDEJ10S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJJGWIRITnCU8520VwWmYy287H0CaagfY',
    appId: '1:364268621894:android:f6723e40fee8ae1c28ba47',
    messagingSenderId: '364268621894',
    projectId: 'socialmediaapp-a0b5f',
    storageBucket: 'socialmediaapp-a0b5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-KKlYLUj04zwF7jU2h9YxTIKpRSvxRLs',
    appId: '1:364268621894:ios:923dbb641eb19e6928ba47',
    messagingSenderId: '364268621894',
    projectId: 'socialmediaapp-a0b5f',
    storageBucket: 'socialmediaapp-a0b5f.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-KKlYLUj04zwF7jU2h9YxTIKpRSvxRLs',
    appId: '1:364268621894:ios:923dbb641eb19e6928ba47',
    messagingSenderId: '364268621894',
    projectId: 'socialmediaapp-a0b5f',
    storageBucket: 'socialmediaapp-a0b5f.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASvV10gIi5HMkCKmcW-erD7arwltzycxw',
    appId: '1:364268621894:web:cf075796f9b38d3b28ba47',
    messagingSenderId: '364268621894',
    projectId: 'socialmediaapp-a0b5f',
    authDomain: 'socialmediaapp-a0b5f.firebaseapp.com',
    storageBucket: 'socialmediaapp-a0b5f.firebasestorage.app',
    measurementId: 'G-SP61Y7RD8D',
  );
}
